name: v2_sales_report_old
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliding_up_panel: ^1.0.2
  responsive_grid: ^1.2.1+1
  syncfusion_flutter_datepicker: ^18.3.40-beta
  provider: ^4.3.2+2
  csv: ^4.0.3
  dio: ^3.0.10
  http: ^0.12.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
