name: v2_sales_report_old
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliding_up_panel: ^1.0.2
  responsive_grid: ^1.2.1+1
  syncfusion_flutter_datepicker: ^18.3.40-beta
  provider: ^4.3.2+2
  csv: ^4.0.3
  http: ^0.12.0+4
  freezed_annotation: ^0.12.0
  dartz: ^0.9.2
  flutter_bloc: ^3.2.0
  firebase_core: ^0.5.0+1
  firebase_auth: ^0.18.1+2
  firebase_analytics: ^6.0.2
  google_sign_in: ^4.5.5
  get_it: ^5.0.1
  injectable: ^1.0.5
  uuid: ^2.0.4
  auto_route: ^0.6.9
  flushbar: ^1.10.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.3
  freezed: ^0.12.2
  lint: ^1.3.0
  injectable_generator: ^1.0.6
  auto_route_generator: ^0.6.9


flutter:
  uses-material-design: true
