name: Flutter Firebase CI CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1

      - name: Set up Java Environment
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - name: Set up Flutter environment
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta' # 'dev', 'alpha', default to: 'stable'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web --release
      - run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}

